# Generated by Django 3.1.3 on 2020-12-04 16:31

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название инградиента')),
                ('dimension', models.CharField(blank=True, max_length=10, verbose_name='Мера измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('title'))],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин')], max_length=10)),
                ('color', models.CharField(blank=True, choices=[('orange', 'Оранжевый'), ('green', 'Зеленый'), ('purple', 'Фиолетовый')], max_length=10, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tag', 'color'), name='tags_color_pairs'),
        ),
    ]
